import Head from 'next/head';

export default function Contact() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='text-background flex flex-col gap-16 mb-16 pt-16'>
                
            </main>
        </>
    )
}
