import Button from '@/components/button';
import ChosingCards from '@/components/chosingCards';
import Heading from '@/components/heading';
import Testimonials from '@/components/testimonials';
import Head from 'next/head';
import { motion } from "framer-motion";
import { Carousel } from '@mantine/carousel';
import {slide, pop} from '@/utils/animation';
import { useLottie } from "lottie-react";
import * as team from '../utils/72259-team.json';
import TextAnimation from '@/components/TextAnimation';

export default function Home() {
  const loadingAnimation = {
    initial: {
      opacity: 0,
    },
    animate: {
      opacity: 1,
      translateX: 0 
    },
    transition: {
      type: 'linear',
      duration: 0.5 
    }
  };

  const items = [
    {
      text: 'I was extremely impressed with the level of professionalism and expertise shown by the team. They were able to take my vision and turn it into a beautiful and functional website that exceeded my expectations.',
      writer: 'Roula M',
      role: 'Legacy Usability Manager',
    },
    {
      text: 'responsive and always available to answer any questions I had throughout the project. Their attention to detail was impressive, and the final product was top-notch.',
      writer: 'Jake',
      role: 'Senior Paradigm Strategist',
    },
    {
      text: "The team was able to deliver my project on time and within budget. I was very pleased with the final product and have received positive feedback from my customers.",
      writer: 'George B',
      role: 'Legacy Usability Manager',
    },
    {
      text: 'They provided valuable insights and recommendations throughout the project, which helped to improve the overall result.',
      writer: 'Kate',
      role: 'Senior Business Strategist',
    },
    {
      text: 'very creative and open to trying new ideas. They were able to bring a fresh perspective to my project and helped me to achieve my goals.',
      writer: 'T.H',
      role: 'Senior Business Strategist',
    },
    {
      text: 'very knowledgeable and able to navigate the constantly changing digital landscape with ease. They were able to provide me with a cutting-edge solution that helped my business to stand out.',
      writer: 'James',
      role: 'Senior Business Strategist',
    },
    {
      text: 'The team was able to provide a comprehensive service that covered all aspects of my project, from design to development and launch. Their holistic approach was very helpful and made the process much smoother',
      writer: 'Thomas',
      role: 'Senior Business Strategist',
    },
  ]

  const options = {
    animationData: team,
    loop: true
  };

  const { View } = useLottie(options);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='text-background flex flex-col gap-16 mb-16'>
        {/* hero Section */}
        <div className='flex gap-8 sm:content-center	sm:items-center py-24 max-sm:flex-col-reverse max-sm:w-full'>
          <motion.div initial={{ opacity: loadingAnimation.initial.opacity, translateX: -100 }} animate={ loadingAnimation.animate } transition={loadingAnimation.transition} className='sm:w-1/2 flex flex-col gap-4'>
            <Heading>
              <div className='flex gap-2'>
                <TextAnimation text='Cyber'/> 
                <span className='text-main'>
                  <TextAnimation text='Craft'/>
                </span> 
                <TextAnimation text="Agency"/>
              </div>
            </Heading>
            <Heading type='h2'>
              Crafting digital solutions for a connected world!!
            </Heading>
            <div>
              A premier digital agency dedicated to helping businesses succeed in the ever-evolving digital landscape. In today&apos;s world, a strong online presence is essential to any business&apos;s success, and we specialize in creating customized digital solutions to help our clients achieve their goals.
            </div>
            <div>
              <Button link='/services'>More details</Button>
            </div>
          </motion.div>
          <motion.div initial={{ opacity:loadingAnimation.initial.opacity, translateX: 100 }} animate={loadingAnimation.animate} transition={loadingAnimation.transition} className='sm:w-1/2 relative h-contain'>
            {/* <Image src='./home/reshot-illustration-website-design-team-K5VSWPFRC7.svg' alt="Website Team" fill/> */}
            { View }
          </motion.div>
        </div>
        {/* about section */}
        <motion.div initial="offscreen" whileInView="onscreen" viewport={{ once: true, amount: 0.5 }} className='flex flex-col gap-16 overflow-hidden'>
          <motion.div variants={slide(-100)} className='flex gap-8 items-center max-sm:flex-col'>
            <img className='rounded-2xl sm:w-1/2' src={`./home/team.jpg`}/>
            <div className='flex flex-col gap-4'>
              <Heading><span className='text-main'>Our</span> Team</Heading>
              <p>Our team of experts is passionate about delivering cutting-edge technology and creative solutions to help our clients grow their online presence and achieve their business objectives. From website design and development to digital marketing and branding, we have the skills and expertise to provide our clients with a comprehensive suite of digital services.</p>
            </div>
          </motion.div>
          <motion.div variants={slide(100)} className='flex flex-row-reverse gap-8 items-center max-sm:flex-col'>
            <img className='rounded-2xl sm:w-1/2' src={`./home/services.jpg`}/>
            <div className='flex flex-col gap-4'>
              <Heading><span className='text-main'>Our</span> Services</Heading>
              <Heading type='h2'>We offer the best services</Heading>
              <div>
                Unlock your business full potential. From custom websites to strategy, our team of experts will help your company thrive online.
                Let us craft your unique presence and drive results from A to Z.
              </div>
              <div>
                <Button link='/'>See more</Button>
              </div>
            </div>
          </motion.div>
        </motion.div>
        {/* why chose us data */}
        <motion.div initial="offscreen" whileInView="onscreen" viewport={{ once: true, amount: 0.8 }} className='flex flex-col gap-16'>
          <motion.div className='flex justify-center'>
            <Heading><span className='text-main'>Why</span> chose <span className='text-main'>Us</span></Heading>
          </motion.div>
          <motion.div variants={pop()} className='grid sm:grid-cols-2 gap-8'>
            <ChosingCards heading='Skilled Professionals'>At Cyber Crafts Agency, we understand the importance of staying ahead of the curve in the digital landscape. That&apos;s why we bring a team of highly skilled and experienced professionals to the table, ensuring that your project is in the best hands.</ChosingCards>
            <ChosingCards heading='Latest Technology'>Our experts have a deep understanding of the latest industry trends and will work closely with you to create tailored solutions that meet your unique business needs and goals.</ChosingCards>
            <ChosingCards heading='Expertise and Experience'>From website design and development, to digital marketing, mobile app development, video production and more. We have the expertise and experience to help your business succeed in the digital world.</ChosingCards>
            <ChosingCards heading='Trusted'>Trust us to craft digital solutions that drive success and elevate your business to the next level.</ChosingCards>
          </motion.div>
        </motion.div>
        {/* testimonials */}
        <div className='flex flex-col gap-16 items-center'>
          <div className='flex justify-center'>
            <Heading>Testimonials</Heading>
          </div>
          <div>
            {/* <AliceCarousel autoWidth autoHeight infinite mouseTracking items={items} autoPlay={ true } autoPlayInterval={ 5000 }/> */}
            <Carousel maw={320} loop mx="auto" withIndicators height={`auto`}>
              {items.map((item, index) => {
                return (<Carousel.Slide key={index}>
                  <Testimonials text={ item.text } writer={ item.writer } role={ item.role }/>
                </Carousel.Slide>)
              })}
            </Carousel>
          </div>
        </div>
      </main>
    </>
  )
}
