import Heading from '@/components/heading';
import Head from 'next/head';
import ServiceCard from '@/components/serviceCard';

export default function Services() {

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className='text-background flex flex-col gap-16 mb-16 pt-16'>
                <Heading className="flex justify-center w-full gap-4">Our <span className='text-main'>Services</span></Heading>
                <div className='grid sm:grid-cols-3 gap-8'>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Website Development' text='Creating and developing custom websites to meet the specific needs of clients. This can include design and layout, content creation, and coding.'/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Search engine optimization (SEO)' text={`Helping clients improve their website's visibility on search engines by optimizing the website's content and structure.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Pay-per-click advertising (PPC)' text={`Creating, managing, and optimizing campaigns on platforms to drive traffic to the client's website.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Social media marketing' text={`Creating and managing social media campaigns for clients on platforms to increase brand awareness and engagement.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Email marketing' text={`Designing, building and sending email campaigns to promote products or services, build customer relationships and drive sales.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Content marketing' text={`Creating and distributing valuable and relevant content that aims to attract, engage and convert target audiences`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='E-commerce solutions' text={`Creating, designing and developing e-commerce platforms to sell products or services online, with features like shopping cart, payment gateways, and inventory management.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Digital strategy consulting' text={`Working with clients to develop a comprehensive digital strategy, which can include elements such as website design and development, SEO, PPC, social media marketing, and more.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Branding and graphic design' text={`Creating visual elements such as logos, typography and color schemes to establish a strong and consistent brand identity for clients`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Mobile app development' text={`Designing and developing mobile apps for iOS and Android platforms`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Video production' text={`Planning, filming, editing and creating video content to promote products or services, build brand awareness and drive engagement.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Analytics and reporting' text={`Tracking and analyzing data to measure the performance of digital campaigns and make data-driven decisions.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='UI/UX design' text={`Designing user interfaces and user experience to improve the usability and accessibility of digital products.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Digital marketing automation' text={`Automating repetitive tasks to improve efficiency and effectiveness of digital marketing campaigns`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Shopify websites' text={`Shopify websites building and consultancy plus integrations.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='WordPress website' text={`WordPress website building and consultancy plus integration.`}/>
                    <ServiceCard Img='https://www.pixelstalk.net/wp-content/uploads/2016/07/Wallpapers-pexels-photo.jpg' Heading='Design packaging' text={`Creating visually appealing and functional packaging for products.`}/>
                </div>
            </main>
        </>
    )
}
